- name: Installation of nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
# - name: Enable the nginx 
#   ansible.builtin.service:
#     name: nginx
#     state: started
#     enabled: yes
- name: delete the default website
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: run app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req
    
- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - restart nginx
# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted